[project]
name = "pathaia"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
version = "0.2.7"
dependencies = [
    "numpy (>=2.0.0,<3.0)",
    "opencv-python-headless (>=4.12.0.88,<4.13.0.0)",
    "tqdm (>=4.67.1,<5.0)",
    "pandas (>=2.2.2,<3.0.0)",
    "fastcore (>=1.3,<2.0)",
    "matplotlib (>=3.5,<4.0)",
    "scikit-image (>=0.25.2,<0.26)",
    "shapely (>=2.1.1,<3.0.0)",
    "opencv-contrib-python (>=4.12.0.88,<4.13.0.0)",
    "pyogrio~=0.9.0",
    "pyarrow~=17.0.0",
    "openslide-python>=1.4.2",
    "openslide-bin>=4.0.0",
    "scikit-learn(>=1,<2)",
    "sortedcontainers(>=2.4.0,<3.0.0)"
]

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"
