name: Publish on PyPI when a release is published

on: 
  release:
    types: [published]
    
jobs:
  builds-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@master
      
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.17
       
      - name: Install pypa/build
        run: python -m pip install build --user
      
      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/ .
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      
